NEMO/apps/contracts/urls.py
from django.urls import path

from NEMO.apps.contracts.views import contracts

urlpatterns = [
    # Contracts and procurements
    path("service_contracts/", contracts.service_contracts, name="service_contracts"),
    path(
        "service_contracts/<int:service_contract_id>/renew/",
        contracts.service_contract_renew,
        name="service_contract_renew",
    ),
    path("procurements/", contracts.procurements, name="procurements"),
    path("contractors/", contracts.contractors, name="contractor_agreements"),
    path(
        "contractors/<int:contractor_agreement_id>/renew/",
        contracts.contractor_agreement_renew,
        name="contractor_agreement_renew",
    ),
    # Reminders and periodic events
    path("email_contract_reminders/", contracts.email_contract_reminders, name="email_contract_reminders"),
]

NEMO/urls.py
import logging
import os
from importlib import import_module

from django.apps import apps
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, re_path
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.views.generic import RedirectView
from django.views.static import serve
from rest_framework import routers

from NEMO.decorators import any_staff_required
from NEMO.models import ReservationItemType
from NEMO.views import (
    abuse,
    access_requests,
    accounts_and_projects,
    adjustment_requests,
    alerts,
    api,
    api_file_import,
    area_access,
    authentication,
    buddy_requests,
    calendar,
    charge_validation,
    configuration_agenda,
    consumables,
    contact_staff,
    customization,
    documents,
    email,
    event_details,
    feedback,
    get_projects,
    history,
    jumbotron,
    knowledge_base,
    landing,
    maintenance,
    mobile,
    news,
    qualifications,
    remote_work,
    resources,
    safety,
    shadowing_verification,
    sidebar,
    status_dashboard,
    tasks,
    timed_services,
    tool_control,
    tool_credentials,
    training,
    training_new,
    tutorials,
    usage,
    user_requests,
    users,
)
from NEMO.views.constants import MEDIA_PROTECTED

logger = logging.getLogger(__name__)


def sort_urls(url_path):
    return url_path[0].count("/"), url_path[0]


# REST API URLs
router = routers.DefaultRouter()
router.register(r"account_types", api.AccountTypeViewSet)
router.register(r"accounts", api.AccountViewSet)
router.register(r"adjustment_requests", api.AdjustmentRequestViewSet)
router.register(r"alert_categories", api.AlertCategoryViewSet)
router.register(r"alerts", api.AlertViewSet)
router.register(r"area_access_records", api.AreaAccessRecordViewSet)
router.register(r"areas", api.AreaViewSet)
router.register(r"auth_groups", api.GroupViewSet)
router.register(r"auth_permissions", api.PermissionViewSet)
router.register(r"billing", api.BillingViewSet, basename="billing")
router.register(r"buddy_requests", api.BuddyRequestViewSet)
router.register(r"configurations", api.ConfigurationViewSet)
router.register(r"configuration_precursors", api.ConfigurationPrecursorViewSet)
router.register(r"configuration_precursor_slots", api.ConfigurationPrecursorSlotViewSet)
router.register(r"configuration_precursor_schedules", api.ConfigurationPrecursorScheduleViewSet)
router.register(r"consumable_categories", api.ConsumableCategoryViewSet)
router.register(r"consumable_withdrawals", api.ConsumableWithdrawViewSet)
router.register(r"consumables", api.ConsumableViewSet)
router.register(r"content_types", api.ContentTypeViewSet)
router.register(r"interlock_card_categories", api.InterlockCardCategoryViewSet)
router.register(r"interlock_cards", api.InterlockCardViewSet)
router.register(r"interlocks", api.InterlockViewSet)
router.register(r"physical_access_levels", api.PhysicalAccessLevelViewSet)
router.register(r"temporary_physical_access_requests", api.TemporaryPhysicalAccessRequestViewSet)
router.register(r"project_disciplines", api.ProjectDisciplineViewSet)
router.register(r"projects", api.ProjectViewSet)
router.register(r"qualification_levels", api.QualificationLevelViewSet)
router.register(r"qualifications", api.QualificationViewSet)
router.register(r"recurring_consumable_charges", api.RecurringConsumableChargesViewSet)
router.register(r"reservations", api.ReservationViewSet)
router.register(r"reservation_configuration_options", api.ConfigurationOptionViewSet)
router.register(r"resources", api.ResourceViewSet)
router.register(r"scheduled_outages", api.ScheduledOutageViewSet)
router.register(r"staff_charges", api.StaffChargeViewSet)
router.register(r"tasks", api.TaskViewSet)
router.register(r"tools", api.ToolViewSet)
router.register(r"tool_credentials", api.ToolCredentialsViewSet)
router.register(r"tool_status", api.ToolStatusViewSet, basename="tool_status")
router.register(r"training_events", api.TrainingEventViewSet)
router.register(r"training_sessions", api.TrainingSessionViewSet)
router.register(r"training_techniques", api.TrainingTechniqueViewSet)
router.register(r"usage_events", api.UsageEventViewSet)
router.register(r"users", api.UserViewSet)
router.registry.sort(key=sort_urls)

reservation_item_types = f'(?P<item_type>{"|".join(ReservationItemType.values())})'

urlpatterns = []

# Include urls for all NEMO plugins (that start with prefix NEMO)
# URLs in plugins with exact same path will take precedence over regular NEMO URLs
# Note that the path MUST be the same, down to the last "/"
for app in apps.get_app_configs():
    app_name = app.name
    if app_name != "NEMO" and app_name.startswith("NEMO"):
        try:
            mod = import_module("%s.urls" % app_name)
        except ModuleNotFoundError:
            logger.warning(f"no urls found for NEMO plugin: {app_name}")
            pass
        except Exception as e:
            logger.exception(f"could not import urls for NEMO plugin: {app_name}")
            pass
        else:
            urlpatterns += [path("", include("%s.urls" % app_name))]
            logger.debug(f"automatically including urls for plugin: {app_name}")

# The order matters for some tests to run properly
urlpatterns += [
    # Authentication & error pages:
    path("login/", authentication.login_user, name="login"),
    path(
        "logout/", LogoutView.as_view(next_page="landing" if not settings.LOGOUT_REDIRECT_URL else None), name="logout"
    ),
    path("impersonate/", authentication.impersonate, name="impersonate"),
    path("authorization_failed/", authentication.authorization_failed, name="authorization_failed"),
    # Root URL defaults to the calendar page on desktop systems, and the mobile homepage for mobile devices:
    path("", landing.landing, name="landing"),
    # Get a list of projects for a user:
    path(
        "get_projects_for_consumables/", get_projects.get_projects_for_consumables, name="get_projects_for_consumables"
    ),
    path("get_projects_for_training/", get_projects.get_projects_for_training, name="get_projects_for_training"),
    path(
        "get_projects_for_tool_control/",
        get_projects.get_projects_for_tool_control,
        name="get_projects_for_tool_control",
    ),
    path("get_projects_for_self/", get_projects.get_projects_for_self, name="get_projects_for_self"),
    # User Profile:
    path("user/view_user/<int:user_id>/", users.view_user, name="view_user"),
    # Tool control:
    # This tool_control URL is needed to be able to reverse when choosing items on mobile using next_page.
    # (see choose_item.html for details)
    re_path(r"^tool_control/(?P<item_type>(tool))/(?P<tool_id>\d+)/$", tool_control.tool_control, name="tool_control"),
    path("tool_control/<int:tool_id>/", tool_control.tool_control, name="tool_control"),
    path("tool_control/", tool_control.tool_control, name="tool_control"),
    path("tool_status/<int:tool_id>/", tool_control.tool_status, name="tool_status"),
    path("use_tool_for_other/", tool_control.use_tool_for_other, name="use_tool_for_other"),
    path("tool_configuration/", tool_control.tool_configuration, name="tool_configuration"),
    re_path("tool_configuration/(?P<config_type>slot|)/", tool_control.tool_configuration, name="tool_configuration"),
    path("create_comment/", tool_control.create_comment, name="create_comment"),
    path("hide_comment/<str:comment_id>/", tool_control.hide_comment, name="hide_comment"),
    re_path(
        r"^enable_tool/(?P<tool_id>\d+)/user/(?P<user_id>\d+)/project/(?P<project_id>\d+)/staff_charge/(?P<staff_charge>(true|false))/$",
        tool_control.enable_tool,
        name="enable_tool",
    ),
    path("disable_tool/<int:tool_id>/", tool_control.disable_tool, name="disable_tool"),
    path("enter_wait_list/", tool_control.enter_wait_list, name="enter_wait_list"),
    path("exit_wait_list/", tool_control.exit_wait_list, name="exit_wait_list"),
    path("tool_config_history/<int:tool_id>/", tool_control.tool_config_history, name="tool_config_history"),
    path("usage_data_history/<int:tool_id>/", tool_control.usage_data_history, name="usage_data_history"),
    path("past_comments_and_tasks/", tool_control.past_comments_and_tasks, name="past_comments_and_tasks"),
    path(
        "ten_most_recent_past_comments_and_tasks/<int:tool_id>/",
        tool_control.ten_most_recent_past_comments_and_tasks,
        name="ten_most_recent_past_comments_and_tasks",
    ),
    path(
        "tool_usage_group_question/<int:tool_id>/<str:group_name>/",
        tool_control.tool_usage_group_question,
        name="tool_usage_group_question",
    ),
    path("reset_tool_counter/<int:counter_id>/", tool_control.reset_tool_counter, name="reset_tool_counter"),
    # User requests
    path("user_requests/", user_requests.user_requests, name="user_requests"),
    re_path(
        r"^user_requests/(?P<tab>training|buddy|access|adjustment)/$", user_requests.user_requests, name="user_requests"
    ),
    # Access requests
    path("access_requests/", access_requests.access_requests, name="access_requests"),
    path("create_access_request/", access_requests.create_access_request, name="create_access_request"),
    path("edit_access_request/<int:request_id>/", access_requests.create_access_request, name="edit_access_request"),
    path("export_access_requests/", access_requests.csv_export, name="export_access_requests"),
    path(
        "delete_access_request/<int:request_id>/", access_requests.delete_access_request, name="delete_access_request"
    ),
    # Buddy System
    path("buddy_requests/", buddy_requests.buddy_requests, name="buddy_requests"),

NEMO/apps/contracts/models.py
from datetime import date

from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from NEMO.apps.contracts.customization import ContractsCustomization
from NEMO.models import BaseDocumentModel, BaseModel, User
from NEMO.views.constants import CHAR_FIELD_MAXIMUM_LENGTH, MEDIA_PROTECTED


class Procurement(BaseModel):
    name = models.CharField(max_length=CHAR_FIELD_MAXIMUM_LENGTH, help_text=_("The name of the contract"))
    submitted_date = models.DateField(null=True, blank=True, help_text=_("The date this contract was submitted"))
    award_date = models.DateField(null=True, blank=True, help_text=_("The date this contract was awarded"))
    contract_number = models.CharField(
        null=True, blank=True, max_length=CHAR_FIELD_MAXIMUM_LENGTH, help_text=_("The contract number")
    )
    requisition_number = models.CharField(
        null=True,
        blank=True,
        max_length=CHAR_FIELD_MAXIMUM_LENGTH,
        help_text=_("The requisition number for this contract"),
    )
    cost = models.DecimalField(
        null=True, blank=True, decimal_places=2, max_digits=14, help_text=_("The cost of this contract")
    )
    notes = models.TextField(null=True, blank=True)

    def display_name(self):
        return self.name

    def display_cost(self):
        if self.cost:
            return f"{self.cost:,.2f}"

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class ServiceContract(Procurement):
    current_year = models.PositiveIntegerField(
        default=1, validators=[MinValueValidator(1)], help_text=_("The total number of years of this service contract")
    )
    total_years = models.PositiveIntegerField(
        default=1, validators=[MinValueValidator(1)], help_text=_("The current year for this service contract")
    )
    start = models.DateField(null=True, blank=True, help_text=_("The start date of this service contract"))
    end = models.DateField(null=True, blank=True, help_text=_("The end date of this service contract"))
    reminder_date = models.DateField(null=True, blank=True, help_text=_("The reminder date for this service contract"))

    def display_name(self):
        return f"{self.name}"

    def display_current_year(self):
        return f"{self.current_year} of {self.total_years}"

    def is_expired(self):
        return self.end and date.today() >= self.end

    def is_warning(self):
        return self.reminder_date and self.end and self.reminder_date <= date.today() < self.end

    def is_active(self):
        return self.start and self.end and self.start <= date.today() <= self.end

    def clean(self):
        if self.current_year > self.total_years:
            raise ValidationError(
                {"current_year": "The current year must be less or equal to the total number of years"}
            )


class ContractorAgreement(BaseModel):
    name = models.CharField(max_length=CHAR_FIELD_MAXIMUM_LENGTH, help_text=_("The name of the contractor"))
    contract = models.ForeignKey(
        Procurement,
        null=True,
        blank=True,
        help_text=_("The contract this contractor is linked to"),
        on_delete=models.CASCADE,
    )
    start = models.DateField(null=True, blank=True, help_text=_("Start date of the contractor agreement"))
    end = models.DateField(null=True, blank=True, help_text=_("The end date of this contractor agreement"))
    reminder_date = models.DateField(
        null=True, blank=True, help_text=_("The reminder date for this contractor agreement")
    )
    notes = models.TextField(null=True, blank=True)

    @property
    def contract_name(self) -> str:
        if self.contract:
            return self.contract.name
        else:
            return ContractsCustomization.get("contracts_contractors_default_empty_label")

    @property
    def contract_number(self) -> str:
        if self.contract:
            return self.contract.contract_number

    def is_expired(self):
        return self.end and date.today() >= self.end

    def is_warning(self):
        return self.reminder_date and self.end and self.reminder_date <= date.today() < self.end

    def is_active(self):
        return self.start and self.end and self.start <= date.today() <= self.end

    def __str__(self):
        return f"{self.name} ({self.contract_name})"

    class Meta:
        ordering = ["contract", "-start"]


class ProcurementDocuments(BaseDocumentModel):
    procurement = models.ForeignKey(Procurement, on_delete=models.CASCADE)

    def get_filename_upload(self, filename):
        from django.template.defaultfilters import slugify

        name = slugify(self.procurement.name)
        type_name = "service_contracts" if isinstance(self.procurement, ServiceContract) else "procurements"
        return f"{MEDIA_PROTECTED}/{type_name}/{name}/{filename}"

    class Meta(BaseDocumentModel.Meta):
        verbose_name_plural = "Procurement documents"


class ContractorAgreementDocuments(BaseDocumentModel):
    contractor_agreement = models.ForeignKey(ContractorAgreement, on_delete=models.CASCADE)

    def get_filename_upload(self, filename):
        from django.template.defaultfilters import slugify

        name = slugify(self.contractor_agreement.name)
        return f"{MEDIA_PROTECTED}/contractor_agreements/{name}/{filename}"

    class Meta(BaseDocumentModel.Meta):
        verbose_name_plural = "Contractor agreement documents"

NEMO/apps/contracts/templates/contracts/contractors.html
{% extends 'contracts/contracts_and_procurements.html' %}
{% load custom_tags_and_filters %}
{% block add_button %}
    {% admin_add_url 'contracts' 'contractoragreement' request.path as add_contractors_url %}
    {% if add_contractors_url %}
        {% button type="add" value="Add" url=add_contractors_url %}
    {% endif %}
{% endblock %}
{% block pagination_content %}
    <table class="table table-bordered table-align-middle table-striped table-hover thead-light"
           style="margin-bottom: 0">
        <thead>
            <tr>
                <th class="sticky">{% include 'pagination/pagination_column.html' with order_by='name' name='Contractor' %}</th>
                <th>{% include 'pagination/pagination_column.html' with order_by='contract__name' name='Contract' %}</th>
                <th>
                    {% include 'pagination/pagination_column.html' with order_by='contract__contract_number' name='Contract number' %}
                </th>
                <th>{% include 'pagination/pagination_column.html' with order_by='start' name='Start' %}</th>
                <th>{% include 'pagination/pagination_column.html' with order_by='natural_end' name='End' %}</th>
                <th>{% include 'pagination/pagination_column.html' with order_by='reminder_date' name='Reminder' %}</th>
                <th class="text-right button-column-minimum">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for contractor_agreement in page %}
                <tr class="{% if contractor_agreement.is_expired %}danger{% elif contractor_agreement.is_warning %}warning{% else %}default{% endif %}">
                    <td class="sticky">{{ contractor_agreement.name }}</td>
                    <td>{{ contractor_agreement.contract_name }}</td>
                    <td>{{ contractor_agreement.contract_number|default_if_none:"" }}</td>
                    <td>{{ contractor_agreement.start|date:"SHORT_DATE_FORMAT" }}</td>
                    <td>{{ contractor_agreement.end|date:"SHORT_DATE_FORMAT" }}</td>
                    <td>{{ contractor_agreement.reminder_date|date:"SHORT_DATE_FORMAT" }}</td>
                    <td class="text-right text-nowrap">
                        {% if contractor_agreement.notes %}
                            {% button icon="glyphicon-info-sign" type="warn" size="small" value="Notes" title=contractor_agreement.notes|default_if_none:""|linebreaksbr data_toggle="tooltip-notes" %}
                        {% endif %}
                        {% if contractor_agreement.contractoragreementdocuments_set.all %}
                            <form method="post" style="display: inline">
                                {% csrf_token %}
                                <input type="hidden" name="title" value="{{ contractor_agreement.name }} contractor documents">
                                {% for document in contractor_agreement.contractoragreementdocuments_set.all %}
                                    {% with content_type=document|content_type %}
                                        <input type="hidden" name="document_info" value="{{ content_type.id }}__{{ document.id }}">
                                    {% endwith %}
                                {% endfor %}
                                {% button icon="glyphicon-list-alt" size="small" type="export" value="Docs" onclick="document_view(this.form);" %}
                            </form>
                        {% endif %}
                        {% admin_edit_url contractor_agreement request.path as change_contractors_url %}
                        {% if change_contractors_url %}
                            {% button size="small" type="edit" value="Edit" url=change_contractors_url %}
                        {% endif %}
                        {% if perms.contracts.change_contractoragreement %}
                            {% url "contractor_agreement_renew" contractor_agreement.id as renew_contractor_agreement_url %}
                            {% button icon="glyphicon-refresh" size="small" type="default" value="Renew" url=renew_contractor_agreement_url %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block table_empty_content %}You do not have any contractor agreements.{% endblock %}

NEMO/apps/contracts/templates/contracts/procurements.html
{% extends 'contracts/contracts_and_procurements.html' %}
{% load custom_tags_and_filters %}
{% block add_button %}
    {% admin_add_url 'contracts' 'procurement' request.path as add_procurement_url %}
    {% if add_procurement_url %}
        {% button type="add" value="Add" url=add_procurement_url %}
    {% endif %}
{% endblock %}
{% block pagination_content %}
    <table class="table table-bordered table-align-middle table-striped table-hover thead-light"
           style="margin-bottom: 0">
        <thead>
            <tr>
                <th class="sticky">{% include 'pagination/pagination_column.html' with order_by='name' name='General info' %}</th>
                <th>{% include 'pagination/pagination_column.html' with order_by='submitted_date' name='Submitted date' %}</th>
                <th>{% include 'pagination/pagination_column.html' with order_by='award_date' name='Award date' %}</th>
                <th>{% include 'pagination/pagination_column.html' with order_by='contract_number' name='Contract number' %}</th>
                <th>{% include 'pagination/pagination_column.html' with order_by='requisition_number' name='Requisition number' %}</th>
                <th>{% include 'pagination/pagination_column.html' with order_by='cost' name='Cost' %}</th>
                <th class="text-right button-column-minimum">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for procurement in page %}
                <tr class="default">
                    <td class="sticky">{{ procurement.display_name }}</td>
                    <td>{{ procurement.submitted_date|date:"SHORT_DATE_FORMAT" }}</td>
                    <td>{{ procurement.award_date|date:"SHORT_DATE_FORMAT" }}</td>
                    <td>{{ procurement.contract_number|default_if_none:"" }}</td>
                    <td>{{ procurement.requisition_number|default_if_none:"" }}</td>
                    <td>{{ procurement.display_cost|default_if_none:"" }}</td>
                    <td class="text-right text-nowrap">
                        {% if procurement.notes %}
                            {% button icon="glyphicon-info-sign" type="warn" size="small" value="Notes" title=procurement.notes|default_if_none:""|linebreaksbr data_toggle="tooltip-notes" %}
                        {% endif %}
                        {% if procurement.procurementdocuments_set.all %}
                            <form method="post" style="display: inline">
                                {% csrf_token %}
                                <input type="hidden" name="title" value="{{ procurement.name }} procurement documents">
                                {% for document in procurement.procurementdocuments_set.all %}
                                    {% with content_type=document|content_type %}
                                        <input type="hidden" name="document_info" value="{{ content_type.id }}__{{ document.id }}">
                                    {% endwith %}
                                {% endfor %}
                                {% button icon="glyphicon-list-alt" size="small" type="export" value="Docs" onclick="document_view(this.form);" %}
                            </form>
                        {% endif %}
                        {% admin_edit_url procurement request.path as change_procurement_url %}
                        {% if change_procurement_url %}
                            {% button size="small" type="edit" value="Edit" url=change_procurement_url %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block table_empty_content %}You do not have any procurements.{% endblock %}

NEMO/apps/contracts/templates/contracts/service_contracts.html
{% extends 'contracts/contracts_and_procurements.html' %}
{% load custom_tags_and_filters %}
{% block add_button %}
    {% admin_add_url 'contracts' 'servicecontract' request.path as add_service_contract_url %}
    {% if add_service_contract_url %}
        {% button type="add" value="Add" url=add_service_contract_url %}
    {% endif %}
{% endblock %}
{% block pagination_content %}
    <table class="table table-bordered table-condensed table-align-middle table-striped table-hover thead-light"
           style="margin-bottom: 0">
        <thead>
            <tr>
                <th class="sticky">{% include 'pagination/pagination_column.html' with order_by='name' name='General info' %}</th>
                <th class="text-center">Year</th>
                <th>{% include 'pagination/pagination_column.html' with order_by='submitted_date' name='Submitted' %}</th>
                <th>{% include 'pagination/pagination_column.html' with order_by='award_date' name='Awarded' %}</th>
                <th>
                    {% include 'pagination/pagination_column.html' with order_by='contract_number' name='Contract/Requisition number' %}
                </th>
                <th>{% include 'pagination/pagination_column.html' with order_by='start' name='Start' %}</th>
                <th>{% include 'pagination/pagination_column.html' with order_by='natural_end' name='End' %}</th>
                <th>{% include 'pagination/pagination_column.html' with order_by='reminder_date' name='Reminder' %}</th>
                <th>{% include 'pagination/pagination_column.html' with order_by='cost' name='Cost' %}</th>
                <th class="text-right button-column-minimum">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for service_contract in page %}
                <tr class="{% if service_contract.is_expired %}danger{% elif service_contract.is_warning %}warning{% else %}default{% endif %}">
                    <td class="sticky">{{ service_contract.display_name }}</td>
                    <td class="text-center text-nowrap">{{ service_contract.display_current_year }}</td>
                    <td>{{ service_contract.submitted_date|date:"SHORT_DATE_FORMAT" }}</td>
                    <td>{{ service_contract.award_date|date:"SHORT_DATE_FORMAT" }}</td>
                    <td>
                        {{ service_contract.contract_number|default_if_none:"" }}
                        {% if service_contract.requisition_number %}
                            <br>
                            {{ service_contract.requisition_number|default_if_none:"" }}
                        {% endif %}
                    </td>
                    <td>{{ service_contract.start|date:"SHORT_DATE_FORMAT" }}</td>
                    <td>{{ service_contract.end|date:"SHORT_DATE_FORMAT" }}</td>
                    <td>{{ service_contract.reminder_date|date:"SHORT_DATE_FORMAT" }}</td>
                    <td>{{ service_contract.display_cost|default_if_none:"" }}</td>
                    <td class="text-right text-nowrap">
                        {% if service_contract.notes %}
                            {% button icon="glyphicon-info-sign" type="warn" size="small" value="Notes" title=service_contract.notes|default_if_none:""|linebreaksbr data_toggle="tooltip-notes" %}
                        {% endif %}
                        {% if service_contract.procurementdocuments_set.all %}
                            <form method="post" style="display: inline">
                                {% csrf_token %}
                                <input type="hidden" name="title" value="{{ service_contract.name }} service contract documents">
                                {% for document in service_contract.procurementdocuments_set.all %}
                                    {% with content_type=document|content_type %}
                                        <input type="hidden" name="document_info" value="{{ content_type.id }}__{{ document.id }}">
                                    {% endwith %}
                                {% endfor %}
                                {% button icon="glyphicon-list-alt" size="small" type="export" value="Docs" onclick="document_view(this.form);" %}
                            </form>
                        {% endif %}
                        {% admin_edit_url service_contract request.path as change_servicecontract_url %}
                        {% if change_servicecontract_url %}
                            {% button size="small" type="edit" value="Edit" url=change_servicecontract_url %}
                        {% endif %}
                        {% if perms.contracts.change_servicecontract %}
                            {% url "service_contract_renew" service_contract.id as renew_service_contract_url %}
                            {% button icon="glyphicon-refresh" size="small" type="default" value="Renew" url=renew_service_contract_url %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block table_empty_content %}You do not have any service contracts.{% endblock %}